version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1
      include:
        - "*"
    groups:
      bump-tag-npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "fix"
      include: "scope"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
